---
- name: OpenStack and Network Configuration Setup
  hosts: all
  become: yes  # Ensures commands are run with elevated privileges
  tasks:

    # Enable CRB (CodeReady Builder) repository
    - name: Enable crb repository
      command: dnf config-manager --enable crb

    # Install OpenStack Yoga release
    - name: Install CentOS OpenStack Yoga release
      dnf:
        name: centos-release-openstack-yoga
        state: present

    # Update all packages
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    # Install network scripts package
    - name: Install network-scripts package
      dnf:
        name: network-scripts
        state: present

    # Disable and stop firewalld
    - name: Disable and stop firewalld
      systemd:
        name: firewalld
        enabled: no
        state: stopped

    # Disable and stop NetworkManager
    - name: Disable and stop NetworkManager
      systemd:
        name: NetworkManager
        enabled: no
        state: stopped

    # Enable and start network service
    - name: Enable and start network service
      systemd:
        name: network
        enabled: yes
        state: started

    # Install OpenStack Packstack
    - name: Install OpenStack Packstack
      dnf:
        name: openstack-packstack
        state: present

    # Install tmux
    - name: Install tmux
      dnf:
        name: tmux
        state: present

    # Update /etc/resolv.conf for DNS settings
    - name: Set DNS nameservers in /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "{{ item }}"
        state: present
      loop:
        - "nameserver 8.8.8.8"
        - "nameserver 8.8.4.4"

    # Remove lines between # Add Zeroconf route and # IPv6 initialization
    - name: Remove lines between markers
      replace:
        path: /etc/sysconfig/network-scripts/ifup-eth
        regexp: '(^# Add Zeroconf route.*?\n)(.*?)(# IPv6 initialization\?)'
        replace: '\1\n\3'
        backup: yes    
    
    # Restart network service
    - name: Restart network service
      systemd:
        name: network
        state: restarted

    # Check status of network service
    - name: Check network service status
      command: systemctl status network
      register: network_status

    # Display network service status
    - name: Display network status
      debug:
        var: network_status.stdout
